name: CI Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install backend dependencies
        working-directory: ./blog-list-server
        run: npm ci
      
      - name: Run backend tests
        working-directory: ./blog-list-server
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          TEST_DB_CONNECTION_URL: ${{ secrets.TEST_DB_CONNECTION_URL }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm test
      
      - name: Install frontend dependencies
        working-directory: ./bloglist-frontend
        run: npm ci
      
      - name: Build frontend
        working-directory: ./bloglist-frontend
        run: npm run build
      
      - name: Start backend server
        working-directory: ./blog-list-server
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          TEST_DB_CONNECTION_URL: ${{ secrets.TEST_DB_CONNECTION_URL }}
          PORT: 3001
          SECRET: ${{ secrets.SECRET }}
        run: npm start &
      
      - name: Start frontend server
        working-directory: ./bloglist-frontend
        env:
          VITE_BACKEND_URL: http://localhost:3001
        run: npm run dev &
      
      - name: Install e2e dependencies
        working-directory: ./e2e
        run: npm ci
      
      - name: Install Playwright Browsers
        working-directory: ./e2e
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        working-directory: ./e2e
        run: npx playwright test
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30